import Assets from "@/classes/interfaces/assets";
import AssetsLoaders from './assets-loaders';
const {
  loadBackgroundImage,
  loadBackgroundMusic,
  loadEnemy1,
  loadEnemy2,
  loadEnemy3,
  loadEnemy4,
  loadEnemy5,
  loadEnemy6,
  loadEnemy7,
  loadEnemy8,
  loadEnemy9,
  loadEnemyBulletCircle,
  loadEnemyBulletLaser,
  loadEnemyExplodeAudio,
  loadEnemyMiniExplodeAudio,
  loadExplodeSprite,
  loadMeteor,
  loadMiniEnemy,
  loadPlayer1,
  loadPlayer2,
  loadPlayer3,
  loadPlayer4,
  loadPlayer5,
  loadPlayerBullet,
  loadPlayerExplodeAudio,
  loadPlayerGetHitAudio,
  loadPlayerHitSprite,
  loadShootingAudio
} = AssetsLoaders;

export default function loadAssets(): Assets {
  return {
    backgroundImage: loadBackgroundImage(),
    backgroundMusic: loadBackgroundMusic(),
    enemy1: loadEnemy1(),
    enemy2: loadEnemy2(),
    enemy3: loadEnemy3(),
    enemy4: loadEnemy4(),
    enemy5: loadEnemy5(),
    enemy6: loadEnemy6(),
    enemy7: loadEnemy7(),
    enemy8: loadEnemy8(),
    enemy9: loadEnemy9(),
    enemyBulletCircle: loadEnemyBulletCircle(),
    enemyBulletLaser: loadEnemyBulletLaser(),
    enemyExplodeAudio: loadEnemyExplodeAudio(),
    enemyMini: loadMiniEnemy(),
    enemyMiniExplodeAudio: loadEnemyMiniExplodeAudio(),
    explodeSprite: loadExplodeSprite(),
    meteor: loadMeteor(),
    player1: loadPlayer1(),
    player2: loadPlayer2(),
    player3: loadPlayer3(),
    player4: loadPlayer4(),
    player5: loadPlayer5(),
    playerBullet: loadPlayerBullet(),
    playerExplodeAudio: loadPlayerExplodeAudio(),
    playerHitAudio: loadPlayerGetHitAudio(),
    playerHitSprite: loadPlayerHitSprite(),
    shootingAudio: loadShootingAudio()
  };
}
