import Assets from "@/classes/interfaces/assets";
import AssetsLoaders from "./assets-loaders";
const {
  loadBackgroundImage,
  loadBackgroundMusic1,
  loadBackgroundMusic2,
  loadBackgroundMusic3,
  loadEnemy1,
  loadEnemy2,
  loadEnemy3,
  loadEnemy4,
  loadEnemy5,
  loadEnemy6,
  loadEnemy7,
  loadEnemy8,
  loadEnemy9,
  loadEnemyBulletCircle,
  loadEnemyBulletLaser,
  loadEnemyExplodeAudio,
  loadEnemyMiniExplodeAudio,
  loadExplodeSprite,
  loadMeteor,
  loadMiniEnemy,
  loadPlayer1,
  loadPlayer2,
  loadPlayer3,
  loadPlayer4,
  loadPlayer5,
  loadPlayerBullet1,
  loadPlayerBullet2,
  loadPlayerExplodeAudio,
  loadPlayerGetHitAudio,
  loadPlayerHitSprite,
  loadPowerUpAudio,
  loadPowerUp,
  loadShootingAudio
} = AssetsLoaders;

export default function loadAssets(): Assets {
  return {
    backgroundImage: loadBackgroundImage(),
    backgroundMusic1: loadBackgroundMusic1(),
    backgroundMusic2: loadBackgroundMusic2(),
    backgroundMusic3: loadBackgroundMusic3(),
    enemy1: loadEnemy1(),
    enemy2: loadEnemy2(),
    enemy3: loadEnemy3(),
    enemy4: loadEnemy4(),
    enemy5: loadEnemy5(),
    enemy6: loadEnemy6(),
    enemy7: loadEnemy7(),
    enemy8: loadEnemy8(),
    enemy9: loadEnemy9(),
    enemyBulletCircle: loadEnemyBulletCircle(),
    enemyBulletLaser: loadEnemyBulletLaser(),
    enemyExplodeAudio: loadEnemyExplodeAudio(),
    enemyMini: loadMiniEnemy(),
    enemyMiniExplodeAudio: loadEnemyMiniExplodeAudio(),
    explodeSprite: loadExplodeSprite(),
    meteor: loadMeteor(),
    player1: loadPlayer1(),
    player2: loadPlayer2(),
    player3: loadPlayer3(),
    player4: loadPlayer4(),
    player5: loadPlayer5(),
    playerBullet1: loadPlayerBullet1(),
    playerBullet2: loadPlayerBullet2(),
    playerExplodeAudio: loadPlayerExplodeAudio(),
    playerHitAudio: loadPlayerGetHitAudio(),
    playerHitSprite: loadPlayerHitSprite(),
    playerPowerUp: loadPowerUp(),
    playerPowerUpAudio: loadPowerUpAudio(),
    shootingAudio: loadShootingAudio()
  };
}
