import { loadAudio, loadImage } from "@/classes/core/utilities";

enum Assets {
  BACKGROUND = "background.webp",
  BACKGROUND_MUSIC = "background-music.m4a",
  ENEMY_EXPLODE_AUDIO = "enemy-explode.wav",
  ENEMY_MINI_EXPLODE_AUDIO = "enemy-mini-explode.wav",
  EXPLODE_SPRITE = "sprite-explode.webp",
  METEOR = "meteor.webp",
  PLAYER_EXPLODE = "player-explode.wav",
  PLAYER_HIT_AUDIO = "player-get-hit.ogg",
  PLAYER_HIT_SPRITE = "sprite-player-hit.webp",
  PLAYER_POWER_UP = "player-power-up.webp",
  PLAYER_POWER_UP_AUDIO = "player-power-up.ogg",
  PLAYER_SHOOT = "player-shoot.ogg",
  SPRITE_ENEMY_1 = "sprite-enemy-1.webp",
  SPRITE_ENEMY_2 = "sprite-enemy-2.webp",
  SPRITE_ENEMY_3 = "sprite-enemy-3.webp",
  SPRITE_ENEMY_4 = "sprite-enemy-4.webp",
  SPRITE_ENEMY_5 = "sprite-enemy-5.webp",
  SPRITE_ENEMY_6 = "sprite-enemy-6.webp",
  SPRITE_ENEMY_7 = "sprite-enemy-7.webp",
  SPRITE_ENEMY_8 = "sprite-enemy-8.webp",
  SPRITE_ENEMY_9 = "sprite-enemy-9.webp",
  SPRITE_ENEMY_BULLET_CIRCLE = "sprite-enemy-bullet-circle.webp",
  SPRITE_ENEMY_BULLET_LASER = "sprite-enemy-bullet-laser.webp",
  SPRITE_ENEMY_MINI = "sprite-enemy-mini.webp",
  SPRITE_PLAYER_1 = "sprite-player-1.webp",
  SPRITE_PLAYER_2 = "sprite-player-2.webp",
  SPRITE_PLAYER_3 = "sprite-player-3.webp",
  SPRITE_PLAYER_4 = "sprite-player-4.webp",
  SPRITE_PLAYER_5 = "sprite-player-5.webp",
  SPRITE_PLAYER_BULLET_1 = "sprite-player-bullet-1.webp",
  SPRITE_PLAYER_BULLET_2 = "sprite-player-bullet-2.webp"
}

const {
  BACKGROUND,
  BACKGROUND_MUSIC,
  ENEMY_EXPLODE_AUDIO,
  ENEMY_MINI_EXPLODE_AUDIO,
  EXPLODE_SPRITE,
  METEOR,
  PLAYER_EXPLODE,
  PLAYER_HIT_AUDIO,
  PLAYER_HIT_SPRITE,
  PLAYER_POWER_UP,
  PLAYER_POWER_UP_AUDIO,
  PLAYER_SHOOT,
  SPRITE_ENEMY_1,
  SPRITE_ENEMY_2,
  SPRITE_ENEMY_3,
  SPRITE_ENEMY_4,
  SPRITE_ENEMY_5,
  SPRITE_ENEMY_6,
  SPRITE_ENEMY_7,
  SPRITE_ENEMY_8,
  SPRITE_ENEMY_9,
  SPRITE_ENEMY_BULLET_CIRCLE,
  SPRITE_ENEMY_BULLET_LASER,
  SPRITE_ENEMY_MINI,
  SPRITE_PLAYER_1,
  SPRITE_PLAYER_2,
  SPRITE_PLAYER_3,
  SPRITE_PLAYER_4,
  SPRITE_PLAYER_5,
  SPRITE_PLAYER_BULLET_1,
  SPRITE_PLAYER_BULLET_2
} = Assets;

export default {
  loadBackgroundImage: (): HTMLImageElement => loadImage(BACKGROUND),
  loadBackgroundMusic: (): HTMLAudioElement => loadAudio(BACKGROUND_MUSIC),
  loadEnemy1: (): HTMLImageElement => loadImage(SPRITE_ENEMY_1),
  loadEnemy2: (): HTMLImageElement => loadImage(SPRITE_ENEMY_2),
  loadEnemy3: (): HTMLImageElement => loadImage(SPRITE_ENEMY_3),
  loadEnemy4: (): HTMLImageElement => loadImage(SPRITE_ENEMY_4),
  loadEnemy5: (): HTMLImageElement => loadImage(SPRITE_ENEMY_5),
  loadEnemy6: (): HTMLImageElement => loadImage(SPRITE_ENEMY_6),
  loadEnemy7: (): HTMLImageElement => loadImage(SPRITE_ENEMY_7),
  loadEnemy8: (): HTMLImageElement => loadImage(SPRITE_ENEMY_8),
  loadEnemy9: (): HTMLImageElement => loadImage(SPRITE_ENEMY_9),
  loadEnemyBulletCircle: (): HTMLImageElement =>
    loadImage(SPRITE_ENEMY_BULLET_CIRCLE),
  loadEnemyBulletLaser: (): HTMLImageElement =>
    loadImage(SPRITE_ENEMY_BULLET_LASER),
  loadEnemyExplodeAudio: (): HTMLAudioElement => loadAudio(ENEMY_EXPLODE_AUDIO),
  loadEnemyMiniExplodeAudio: (): HTMLAudioElement =>
    loadAudio(ENEMY_MINI_EXPLODE_AUDIO),
  loadExplodeSprite: (): HTMLImageElement => loadImage(EXPLODE_SPRITE),
  loadMeteor: (): HTMLImageElement => loadImage(METEOR),
  loadMiniEnemy: (): HTMLImageElement => loadImage(SPRITE_ENEMY_MINI),
  loadPlayer1: (): HTMLImageElement => loadImage(SPRITE_PLAYER_1),
  loadPlayer2: (): HTMLImageElement => loadImage(SPRITE_PLAYER_2),
  loadPlayer3: (): HTMLImageElement => loadImage(SPRITE_PLAYER_3),
  loadPlayer4: (): HTMLImageElement => loadImage(SPRITE_PLAYER_4),
  loadPlayer5: (): HTMLImageElement => loadImage(SPRITE_PLAYER_5),
  loadPlayerBullet1: (): HTMLImageElement => loadImage(SPRITE_PLAYER_BULLET_1),
  loadPlayerBullet2: (): HTMLImageElement => loadImage(SPRITE_PLAYER_BULLET_2),
  loadPlayerExplodeAudio: (): HTMLAudioElement => loadAudio(PLAYER_EXPLODE),
  loadPlayerGetHitAudio: (): HTMLAudioElement => loadAudio(PLAYER_HIT_AUDIO),
  loadPlayerHitSprite: (): HTMLImageElement => loadImage(PLAYER_HIT_SPRITE),
  loadPowerUp: (): HTMLImageElement => loadImage(PLAYER_POWER_UP),
  loadPowerUpAudio: (): HTMLAudioElement => loadAudio(PLAYER_POWER_UP_AUDIO),
  loadShootingAudio: (): HTMLAudioElement => loadAudio(PLAYER_SHOOT)
};
